language: python
install:
  - pip install pep8
  - pip install https://github.com/dcramer/pyflakes/tarball/master
  - pip install pylint
script:
  - "pep8 ."
  - pyflakes -x W .
  - "pylint ."
  - ./manage.py test