language: python
install:
  - pip install -q pep8
  - pip install -q https://github.com/dcramer/pyflakes/tarball/master
  - pip install -qr requirements.txt --use-mirrors
script:
  - "pep8 ."
  - pyflakes -x W .
  - python manage.py test comments letters users